version: '3.9'
services:
  app:
    build: .
    container_name: app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookstore
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      MYSQL_ROOT_PASSWORD: 20040802

    volumes:
      - ./data:/var/lib/mysql
      - ./bookstore.sql:/docker-entrypoint-initdb.d/bookstore.sql
